### ISSUE TITLE
Error: Cannot find module 'babel-runtime/core-js/object/get-prototype-of'

### ISSUE THREAD

**Issue by Montaldo** [paulcbetts/electron-prebuilt-compile#3]
I am trying to build some skeletons for electron with coffeescript and less. 

Only when adding electron-prebuilt-compile as a dependency instead of electron-prebuilt. It completely breaks.

package.json
`
"dependencies": {
  "electron-prebuilt-compile": "^1.2.2",
  "season": "^5.3"
},
`
`
"devDependencies": {
  "coffee-script": "~1.10.0",
  "cross-env": "^1.0.8",
  "less": "*"
}
`

> App threw an error during load
Error: Cannot find module 'babel-runtime/core-js/object/get-prototype-of'
    at Module._resolveFilename (module.js:438:15)
    at Function.Module._resolveFilename (C:\projectpath\node_modules\electron-prebuilt-compile\node_modules\elec
tron-prebuilt\dist\resources\electron.asar\common\reset-search-paths.js:47:12)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\projectpath\node_modules\electron-prebuilt-compile\node_modules\electron-compile\l
ib\config-parser.js:8:23)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)

This might have to do with the fact that npm complains about jade being deprecated?

**Comment by Montaldo** [comment]
I had to manually add babel-runtime to get it working
